### ISSUE TITLE
npm library is not exist.

### ISSUE THREAD

**Issue by cgrewon** [BunHouth/react-native-ig-image-picker#1]
When try to install using npm, it says there is no this library

**Comment by BunHouth** [comment]
> When try to install using npm, it says there is no this library

you can install from GitHub instead. Once I have time I will make it available for android then will publish to npm

**Comment by BunHouth** [comment]
> When try to install using npm, it says there is no this library

you can found it here https://www.npmjs.com/package/react-native-ig-image-picker
