### ISSUE TITLE
typo error in /ios/IGImagePicker.swift

### ISSUE THREAD

**Issue by Jericazhou** [BunHouth/react-native-ig-image-picker#2]
func name should be libraryPicker rather than libaryPicker
<img width="1194" alt="Screenshot 2021-05-18 at 17 40 57" src="https://user-images.githubusercontent.com/30583268/118629553-44e06700-b800-11eb-9500-8593e318a7b8.png">

**Comment by Jericazhou** [comment]
another one in line 101: should be forKeyPath: "library.numberOfItemsInRow"
<img width="861" alt="Screenshot 2021-05-18 at 17 49 12" src="https://user-images.githubusercontent.com/30583268/118630707-5fffa680-b801-11eb-831e-7a2ab12e7aa1.png">
@BunHouth

**Comment by BunHouth** [comment]
@Jericazhou Thank for your feedback. BTW you can create PR about this issue.
