### ISSUE TITLE
error: package com.jp.bene.app does not exist

### ISSUE THREAD

**Issue by Jericazhou** [BunHouth/react-native-ig-image-picker#4]
[Project_Root]/node_modules/react-native-ig-image-picker/android/src/main/java/com/igimagepicker/RedBookPresenter.java:12: error: package com.jp.bene.app does not exist
import com.jp.bene.app.R;
                                        ^
Do you know how to handle with this?  @BunHouth

**Comment by BunHouth** [comment]
> [Project_Root]/node_modules/react-native-ig-image-picker/android/src/main/java/com/igimagepicker/RedBookPresenter.java:12: error: package com.jp.bene.app does not exist
> import com.jp.bene.app.R;
> ^
> Do you know how to handle with this? @BunHouth

thank for your feedback. I have fixed. Please update to the latest version

**Comment by Jericazhou** [comment]
thanks!
